### ISSUE TITLE
Error establish_benchmark.sh

### ISSUE THREAD

**Issue by AG-Run** [haowenz/LRECE#1]
Hello

Im implementing the LRECE using the E coli and yeast data set to test the tool. I followed the script and compile the LRECE script, then I get the same error even when I run
sh establish_benchmark.sh -e -y -t tmpDir -o benDir and
 sh establish_benchmark.sh -h

It shows
establish_benchmark.sh: 5: Bad substitution
establish_benchmark.sh: 11: source: not found
establish_benchmark.sh: 14: DEFINE_boolean: not found
establish_benchmark.sh: 15: DEFINE_boolean: not found
establish_benchmark.sh: 16: DEFINE_boolean: not found
establish_benchmark.sh: 17: DEFINE_string: not found
establish_benchmark.sh: 18: DEFINE_string: not found
establish_benchmark.sh: 21: FLAGS: not found

Thanks for the help

**Comment by haowenz** [comment]
It looks like a problem of the shell your are using. Can you try the following to see your default shell? 
`readlink -f $(which sh)`

If it is not bash, then can you try to use bash and see if it works?
`bash establish_benchmark.sh -h`
