### ISSUE TITLE
evaluate on my own data

### ISSUE THREAD

**Issue by Beauty9527** [haowenz/LRECE#2]
Dear Haowen,
There is a problem when I use the lrece to evaluate my own corrected long reads, I use the command"sh evaluate_correction.sh -g sh -n 07.fasta -p pb -l 500 -r NC_000913.3.fasta -i correctedReadDir -o outputDir" after all the data were prepared in the same directory path ,the terminal shows like following:
Minimum coverage is 1.
Minimum read length is 500.
Sequencing platform is PacBio.
Reference: NC_000913.3.fasta
Submitted the jobs successfully.
but,there was nothing generated in the next level path of outputDir/stats_07.fasta. Have I lost somthing important in the procedure?Should I have to use the script run-correction.sh to correct reads and generete necessary middle files?
Looking forward your reply,thanks!

**Comment by haowenz** [comment]
"-g sh" makes the job submit with "sh xxxxx &". It will run the job in background for a while before it can generate results. See the below code line https://github.com/haowenz/LRECE/blob/cf3332ee51502b8caacf6cc0337c3fa3f42dac96/src/evaluate_correction.sh#L96
I suggest you check the results after you find the background process of it terminate. If you were using a server, you should keep your connection while the job is running at background. Or you may not get any results.

**Comment by Beauty9527** [comment]
Thanks for your prompt reply. I have got your meaning and it will help me in my graduation greatly.
Best wishes and thanks again.
