### ISSUE TITLE
no output...

### ISSUE THREAD

**Issue by rmormando** [haowenz/LRECE#4]
Hi I am trying to use this tool to correct long reads with short reads and nothing is being output when I go to run this command:

```
sh run_correction_tools.sh -n 'mydata' -p 'ont' -1 R1.fasta -2 R2.fasta -s sr_combined.fasta -l LR.fasta -t tmpDir -o outDir
```

I don't understand why it requires me to use the `-s` flag as I already provide the two short reads necessary but I just combined the data using the `cat` command to combine both short read files into one file.

When I go to run this command this is what is outputted onto the SDOUT:

```
Short read file 1: R1.fasta
Short read file 2: R2.fasta
Short read file: sr_combined.fasta
Long read file: LR.fasta
Temporary directory: tmpDir
Output directory: outDir
```

And then nothing is outputted...no files are changed and nothing is added to the `outDir` directory...can someone please explain what is going on and how I can fix it?

**Comment by haowenz** [comment]
As mentioned in the manual: "Note that you should put the commands to run your error correction tools into the main function of this script."

**Comment by rmormando** [comment]
Okay I copied this command into the main function:
```
sh run_correction_tools.sh -n 'mydata' -p 'ont' -1 R1.fasta -2 R2.fasta -s sr_combined.fasta -l LR.fasta -t tmpDir -o outDir
```

And still nothing happened but now I get this message added on to the end of the STDOUT from above:

```
/home/ec2-user/LRECE/src/shflags: line 759: FLAGS_ARGC: readonly variable
```

**Comment by haowenz** [comment]
I didn't get it. Which command?

**Comment by rmormando** [comment]
This is the command:

sh run_correction_tools.sh -n 'mydata' -p 'ont' -1 R1.fasta -2 R2.fasta -s sr_combined.fasta -l LR.fasta -t tmpDir -o outDir

**Comment by haowenz** [comment]
Let me clarify. LRECE is not an error correction tool. Instead, it is an error correction evaluation tool. This means you have to install the error correction tools yourself. And then put the command lines to run the installed tools into the main properly. After that you can use this command to run the tools.

**Comment by rmormando** [comment]
Oh I misunderstood what the tool does then sorry about that
